In [1]:
import pandas as pd
import metaknowledge as mk

In [2]:
RC = mk.RecordCollection(r'D:\python科学计量可视化\数据\Demo data\Python-PubMed')
RC

In [3]:
df = pd.DataFrame(RC.makeDict())
df.head(3)

,PMID,OWN,STAT,DCOM,LR,IS,VI,IP,DP,TI,...,OID,PMCR,RIN,OAB,OABL,RPI,num-Authors,num-Male,num-Female,num-Unknown
0,PMID:30518809,[NLM],[MEDLINE],[20200626],[20210109],"[1476-5527 (Electronic), 0950-9240 (Linking)]",33,[3],2019 Mar,A systematic review and network meta-analysis ...,...,None,None,None,None,None,None,7,3,4,0
1,PMID:25403604,[NLM],[MEDLINE],[20150305],[20181202],"[1524-4563 (Electronic), 0194-911X (Linking)]",65,[2],2015 Feb,Magnitude of blood pressure reduction in the p...,...,None,None,None,None,None,None,8,8,0,0
2,PMID:28597796,[NLM],[MEDLINE],[20190628],[20190718],"[0001-5385 (Print), 0001-5385 (Linking)]",72,[2],2017 Apr,A1166C polymorphism of the angiotensin II type...,...,None,None,None,None,None,None,6,2,0,4

In [4]:
for i in range(len(df.columns)):
    df.iloc[:,i] = df.iloc[:,i].astype(str)

In [5]:
from sqlalchemy import create_engine
connect = create_engine('mysql+pymysql://root:123@localhost:3306/')
df.to_sql('pubmed',connect,schema='Scientometrics')

2000

In [6]:
pd.read_sql_table('pubmed',connect,schema='Scientometrics')

,index,PMID,OWN,STAT,DCOM,LR,IS,VI,IP,DP,...,OID,PMCR,RIN,OAB,OABL,RPI,num-Authors,num-Male,num-Female,num-Unknown
0,0,PMID:30518809,['NLM'],['MEDLINE'],['20200626'],['20210109'],"['1476-5527 (Electronic)', '0950-9240 (Linking)']",33,['3'],2019 Mar,...,None,None,None,None,None,None,7,3,4,0
1,1,PMID:25403604,['NLM'],['MEDLINE'],['20150305'],['20181202'],"['1524-4563 (Electronic)', '0194-911X (Linking)']",65,['2'],2015 Feb,...,None,None,None,None,None,None,8,8,0,0
2,2,PMID:28597796,['NLM'],['MEDLINE'],['20190628'],['20190718'],"['0001-5385 (Print)', '0001-5385 (Linking)']",72,['2'],2017 Apr,...,None,None,None,None,None,None,6,2,0,4
3,3,PMID:22331252,['NLM'],['MEDLINE'],['20160423'],['20211021'],"['1995-1892 (Print)', '1680-0745 (Electronic)'...",23,['1'],2012 Feb,...,None,None,None,None,None,None,8,0,0,8
4,4,PMID:29318704,['NLM'],['MEDLINE'],['20190909'],['20190909'],"['1099-1557 (Electronic)', '1053-8569 (Linking)']",27,['3'],2018 Mar,...,None,None,None,None,None,None,6,0,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,PMID:28411166,['NLM'],['MEDLINE'],['20171023'],['20181202'],"['1873-0183 (Electronic)', '1568-9972 (Linking)']",16,['6'],2017 Jun,...,None,None,None,None,None,None,11,4,2,5
1996,1996,PMID:29134444,['NLM'],['MEDLINE'],['20180813'],['20181113'],"['1590-3478 (Electronic)', '1590-1874 (Linking)']",39,['2'],2018 Feb,...,None,None,None,None,None,None,6,0,0,6
1997,1997,PMID:29899980,['NLM'],['MEDLINE'],['20180619'],['20181202'],"['2047-2986 (Electronic)', '2047-2978 (Print)'...",8,['1'],2018 Jun,...,None,None,None,None,None,None,7,3,0,4
1998,1998,PMID:32888198,['NLM'],['MEDLINE'],['20201019'],['20210906'],"['1469-493X (Electronic)', '1361-6137 (Linking)']",9,['9'],2020 Sep 5,...,None,None,None,None,None,None,4,2,1,1
1999,1999,PMID:29973178,['NLM'],['MEDLINE'],['20190321'],['20190610'],"['1471-2393 (Electronic)', '1471-2393 (Linking)']",18,['1'],2018 Jul 4,...,None,None,None,None,None,None,9,0,0,9